sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDcNTf97m7DUVmrFLKt
    access-key-secret: qdzezCerfYAYyPMiVJy6gAIXYrm9d0
    bucket-name: wenpeibiao
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx35092071debdb3ae
    secret: c2b7d71e6b4b6bc48e01206d261f7041